rails:
  input:
    flows:
      - classify_and_route
  output:
    flows:
      - check_harmful

    streaming:
      enabled: True
      chunk_size: 20
      context_size: 5
      stream_first: False
